version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: defeed-engine-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-defeed-prod}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-defeed-prod}
      POSTGRES_DB: ${DB_NAME:-defeed}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/pgvector-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-defeed-prod} -d ${DB_NAME:-defeed}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  app:
    container_name: defeed-engine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./.env:/app/.env:ro"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  db_data:
